// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM2vojK6wWDeBwnjJvoEhtXa7Kk_0CBS8',
    appId: '1:632256168381:web:3a4595c24762ef9d1c52d4',
    messagingSenderId: '632256168381',
    projectId: 'hotelio-82e23',
    authDomain: 'hotelio-82e23.firebaseapp.com',
    storageBucket: 'hotelio-82e23.appspot.com',
    measurementId: 'G-R21LQWMME5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGjvwFj_ymOAaC1EK7Nnq6s6hMCJR_Ho0',
    appId: '1:632256168381:android:be6c75d01257630d1c52d4',
    messagingSenderId: '632256168381',
    projectId: 'hotelio-82e23',
    storageBucket: 'hotelio-82e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq3AnuPR5M0jeGUXx8XvMCHm2Ln-Qh9uw',
    appId: '1:632256168381:ios:4b8bc235e88c795d1c52d4',
    messagingSenderId: '632256168381',
    projectId: 'hotelio-82e23',
    storageBucket: 'hotelio-82e23.appspot.com',
    iosClientId: '632256168381-m87acmn2nm92vd5c6ndnafispp506lk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq3AnuPR5M0jeGUXx8XvMCHm2Ln-Qh9uw',
    appId: '1:632256168381:ios:273ccc04f3bb97c41c52d4',
    messagingSenderId: '632256168381',
    projectId: 'hotelio-82e23',
    storageBucket: 'hotelio-82e23.appspot.com',
    iosClientId: '632256168381-7bvmd7h6d6fk0jd1k123umf7og7gvdoo.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio.RunnerTests',
  );
}
